import { useEffect, useMemo, useState } from "react";
import { RiHeartFill, RiHeartLine, RiRefreshLine } from "@remixicon/react";

import { AnimeDetailSheet } from "@/components/anime-detail-sheet";
import { CompactSelect } from "@/components/controls";
import { AnimeGridSkeleton, PageEmpty, PageError } from "@/components/page-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useMarkMutation, useSettings, useWeekly } from "@/hooks/use-calendar";
import { currentDateParts, displayTitle, fallbackCover, mediaLabels, regionOptions, weekState } from "@/lib/anime";
import { timezone } from "@/module-context";
import type { AnimeListItem } from "@/types";

export function WeeklyPage() {
  const query = useWeekly(); const settings = useSettings(); const mark = useMarkMutation(); const today = currentDateParts(timezone()); const [onlyWatching, setOnlyWatching] = useState(false); const [includeContinuing, setIncludeContinuing] = useState(true); const [region, setRegion] = useState("all"); const [expanded, setExpanded] = useState<Set<number>>(new Set()); const [detail, setDetail] = useState<AnimeListItem | null>(null);
  useEffect(() => { if (!settings.data) return; setRegion(settings.data.weeklyRegion); setIncludeContinuing(settings.data.showContinuing); }, [settings.data]);
  const groups = useMemo(() => (query.data?.days ?? []).map((day) => ({ ...day, items: day.items.filter((item) => item.mark_type !== "ignored").filter((item) => !onlyWatching || item.mark_type === "watching").filter((item) => includeContinuing || item.cour_relation !== "continuing").filter((item) => region === "all" || item.region === region) })), [query.data, onlyWatching, includeContinuing, region]);
  const count = groups.reduce((sum, day) => sum + day.items.length, 0); const courMonth = today.month >= 10 ? 10 : today.month >= 7 ? 7 : today.month >= 4 ? 4 : 1;
  return <div className="tn-anime-page"><Card className="tn-anime-weekly-toolbar"><CardContent><div><strong>{today.year}年{courMonth}月新番</strong><span>· {count} 部放送</span></div><div><Button size="sm" variant={onlyWatching ? "secondary" : "outline"} aria-pressed={onlyWatching} onClick={() => setOnlyWatching((value) => !value)}>只看关注</Button><Button size="sm" variant={includeContinuing ? "secondary" : "outline"} aria-pressed={includeContinuing} onClick={() => setIncludeContinuing((value) => !value)}>包含续播</Button><CompactSelect value={region} options={regionOptions} onChange={setRegion} /><Button size="sm" variant="outline" disabled={query.isFetching} onClick={() => void query.refetch()}><RiRefreshLine data-icon="inline-start" />{query.isFetching ? "刷新中" : "刷新周历"}</Button></div></CardContent></Card>
    {query.isError ? <PageError description="无法读取周历数据。" retry={() => void query.refetch()} /> : query.isLoading ? <AnimeGridSkeleton /> : <div className="tn-anime-week-grid">{groups.map((group) => { const state = weekState(group.weekday, today.weekday); const visible = expanded.has(group.weekday) ? group.items : group.items.slice(0, 5); return <Card key={group.weekday} className="tn-anime-week-card" data-state={state}><CardHeader><div><CardTitle>{group.label}</CardTitle>{state === "today" ? <Badge>今天</Badge> : <Badge variant="secondary">{state === "past" ? "已过" : "即将"}</Badge>}</div><span>{group.items.length} 部</span></CardHeader><CardContent>{visible.length ? <div className="tn-anime-week-list">{visible.map((item) => <div role="button" tabIndex={0} key={item.id} className="tn-anime-week-item" onClick={() => setDetail(item)} onKeyDown={(event) => { if (event.target === event.currentTarget && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); setDetail(item); } }}><img src={item.cover_url || fallbackCover(item)} alt="" loading="lazy" onError={(event) => { event.currentTarget.src = fallbackCover(item); }} /><span><strong>{displayTitle(item)}</strong><small><Badge variant="secondary">{mediaLabels[item.media_type]}</Badge><Badge variant="outline">{item.cour_relation_label}</Badge>{item.score ? <em>★ {item.score}</em> : null}</small></span><Button type="button" size="icon-sm" variant={item.mark_type === "watching" ? "default" : "ghost"} aria-label={item.mark_type === "watching" ? "取消关注" : "关注"} onClick={(event) => { event.stopPropagation(); mark.mutate({ item, mark: "watching" }); }}>{item.mark_type === "watching" ? <RiHeartFill /> : <RiHeartLine />}</Button></div>)}</div> : <PageEmpty title="暂无放送" description="这一天没有符合当前条件的作品。" />}{group.items.length > 5 ? <Button className="w-full" variant="ghost" onClick={() => setExpanded((value) => { const next = new Set(value); if (next.has(group.weekday)) next.delete(group.weekday); else next.add(group.weekday); return next; })}>{expanded.has(group.weekday) ? "收起" : `展开剩余 ${group.items.length - 5} 部`}</Button> : null}</CardContent></Card>; })}</div>}
    {!query.isLoading && !query.isError && !count ? <PageEmpty title="周历暂无内容" description="调整筛选条件或刷新周历数据。" /> : null}<AnimeDetailSheet item={detail} onOpenChange={(open) => { if (!open) setDetail(null); }} />
  </div>;
}
